//Generated by SceneFind.cs 
using UnityEditor; 
using UnityEngine; 
namespace Utility { 
public class EditorMapOpener : Editor { 
	[MenuItem("Open Scene/Title Screen", false, 20)]
	private static void MainMenu() {
		OpenIf("Assets/Scenes/Title Screen.unity");
	}
	[MenuItem("Open Scene/Garden-1", false, 20)]
	private static void Level01() {
		OpenIf("Assets/Scenes/Garden-1.unity");
	}
	[MenuItem("Open Scene/Garden-2", false, 20)]
	private static void Level02() {
		OpenIf("Assets/Scenes/Garden-2.unity");
	}
	private static void OpenIf(string level) {
		if (EditorApplication.SaveCurrentSceneIfUserWantsTo()){
			EditorApplication.OpenScene(level);
		}
	}
}
}